site_name: Depp learning
site_url: https://github.com/WonyoungCho/AI
site_description: Tutorial review of Deep learning
repo_url: https://github.com/WonyoungCho/AI/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - Deep Learning:
        - 'Introduction' : 'deeplearning_int.md'
        - 'Example' : 'deeplearning_ex.md'

theme: readthedocs
